---
- name: MicroK8s Installation
  hosts: EC2
  become: yes  # If you need to escalate privileges to run the script

  tasks:
    - name: Install the MicroK8s
      shell: |
        # Install microk8s
        echo "inside snap install"
        sudo snap install microk8s --classic

        sudo microk8s status --wait-ready
        # sudo usermod -a -G microk8s ubuntu
        # sudo chown -R ubuntu ~/.kube

        # #newgrp microk8s

        # cd $HOME
        # mkdir .kube
        # cd .kube
        # sudo microk8s config > config

        # Alias kubectl to microk8s.kubectl
        echo "alias kubectl='microk8s kubectl'" >> ~/.bashrc
        source ~/.bashrc

        # # Print status
        # microk8s.status